FROM node:18 as super-buddy

# Define ARG for app environment variable
ARG APP_SERVER_PORT
ARG DB_TYPE
ARG DB_SERVER
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_DATABASE
ARG DB_MIGRATIONS_RUN_ON_START
ARG IS_PROD
ARG NOTIONBUDDY_FRONTEND_BASE_URL
ARG NOTION_OAUTH_CLIENT_ID
ARG NOTION_OAUTH_CLIENT_SECRET
ARG NOTION_REDIRECT_URI
ARG NOTION_RESPONSE_TYPE
ARG NOTION_OWNER
ARG NOTION_AUTH_URL
ARG NOTIONBUDDY_APP_ID
ARG CANVA_JWKS_URL
ARG NOTION_OAUTH_TOKEN_URL
ARG NOTION_SEARCH_URL
ARG NOTION_VERSION

# Echo each environment variable
RUN echo "APP_SERVER_PORT=$APP_SERVER_PORT" && \
    echo "DB_TYPE=$DB_TYPE" && \
    echo "DB_SERVER=$DB_SERVER" && \
    echo "DB_HOST=$DB_HOST" && \
    echo "DB_PORT=$DB_PORT" && \
    echo "DB_USER=$DB_USER" && \
    echo "DB_PASSWORD=$DB_PASSWORD" && \
    echo "DB_DATABASE=$DB_DATABASE" && \
    echo "DB_MIGRATIONS_RUN_ON_START=$DB_MIGRATIONS_RUN_ON_START" && \
    echo "IS_PROD=$IS_PROD" && \
    echo "NOTIONBUDDY_FRONTEND_BASE_URL=$NOTIONBUDDY_FRONTEND_BASE_URL" && \
    echo "NOTION_OAUTH_CLIENT_ID=$NOTION_OAUTH_CLIENT_ID" && \
    echo "NOTION_OAUTH_CLIENT_SECRET=$NOTION_OAUTH_CLIENT_SECRET" && \
    echo "NOTION_REDIRECT_URI=$NOTION_REDIRECT_URI" && \
    echo "NOTION_RESPONSE_TYPE=$NOTION_RESPONSE_TYPE" && \
    echo "NOTION_OWNER=$NOTION_OWNER" && \
    echo "NOTION_AUTH_URL=$NOTION_AUTH_URL" && \
    echo "NOTIONBUDDY_APP_ID=$NOTIONBUDDY_APP_ID" && \
    echo "CANVA_JWKS_URL=$CANVA_JWKS_URL" && \
    echo "NOTION_OAUTH_TOKEN_URL=$NOTION_OAUTH_TOKEN_URL" && \
    echo "NOTION_SEARCH_URL=$NOTION_SEARCH_URL" && \
    echo "NOTION_VERSION=$NOTION_VERSION"

# Define ARG for Railway environment variable
ARG PORT
ARG MYSQLHOST
ARG MYSQLPORT
ARG MYSQLUSER
ARG MYSQLPASSWORD
ARG MYSQLDATABASE

# Echo each environment variable
RUN echo "PORT=$PORT" && \
    echo "MYSQLHOST=$MYSQLHOST" && \
    echo "MYSQLPORT=$MYSQLPORT" && \
    echo "MYSQLUSER=$MYSQLUSER" && \
    echo "MYSQLPASSWORD=$MYSQLPASSWORD" && \
    echo "MYSQLDATABASE=$MYSQLDATABASE"


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

CMD [ "node", "dist/main.js" ]
