export enum CustomErrorCode {
  ACCESS_TOKEN_VALIDITY = 'UA-ATV',
  DESIGN_TOKEN_VERIFIED = 'UA-DTV',
  NO_DESIGN_VERIFICATION = 'UA-NDV',
  NO_NOTION_ACCESS_TOKEN = 'UA-NAT',
  NOT_REGISTERED_USER = 'UA-NRU',
  UNSUCCESSFUL_DISCONNECTION = 'UD-NAR',
  USER_TOKEN_VERIFIED = 'UA-UTV',
}
